apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whoami

resources:
  - namespace.yaml
  - networkpolicy.yaml

helmCharts:
  - name: whoami
    repo: https://helloviktor.github.io/charts
    version: 0.1.0
    releaseName: whoami
    namespace: whoami
    includeCRDs: true
