apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yaml
  - name: grafana-config
    files:
      - grafana.ini

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment-prometheus.yaml
  - deployment-grafana.yaml
  - service-prometheus.yaml
  - service-grafana.yaml
  - ingress.yaml
