apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yaml

  - name: grafana-config
    files:
      - grafana/grafana.ini

  - name: grafana-datasources
    files:
      - grafana/datasources.yaml

  - name: grafana-dashboards
    files:
      - grafana/dashboards/traefik-rev9.json

  - name: grafana-provision
    files:
      - grafana/provision.yaml

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment-prometheus.yaml
  - deployment-grafana.yaml
  - service-prometheus.yaml
  - service-grafana.yaml
  - ingress.yaml
