apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus/prometheus.yaml

  - name: grafana-config
    files:
      - grafana/grafana.ini

  - name: grafana-datasource-config
    files:
      - grafana/datasources.yaml

  - name: grafana-dashboards
    files:
      - grafana/dashboards/traefik-rev9.json

  - name: grafana-dashboard-config
    files:
      - grafana/dashboards.yaml

resources:
  - deployment-prometheus.yaml
  - deployment-grafana.yaml
  - service-prometheus.yaml
  - service-grafana.yaml
  - networkpolicy-prometheus.yaml
  - networkpolicy-grafana.yaml
  - ingress.yaml
