apiVersion: v2
name: whoami
description: A simple Helm chart for traefik/whoami container. Requires ingressRoute.host to be set for IngressRoute creation.
type: application
version: 0.1.0
appVersion: "v1.11"
