apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkding

images:
  - name: linkding
    newName: ghcr.io/sissbruecker/linkding
    newTag: 1.45.0-alpine

configMapGenerator:
  - name: linkding
    envs:
      - .env

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
