apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: miniflux

resources:
  - networkpolicy.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: miniflux-secrets
    envs:
      - .env

helmCharts:
  - name: miniflux
    repo: https://helloviktor.github.io/charts
    version: 0.1.0
    releaseName: miniflux
    namespace: miniflux
    valuesInline:
      secret:
        create: false
        name: miniflux-secrets
      ingressRoute:
        host: rss.hefler.dev
