apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkding

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: linkding-secrets
    envs:
      - .env

helmCharts:
  - name: linkding
    repo: https://helloviktor.github.io/charts
    version: 0.1.0
    releaseName: linkding
    namespace: linkding
    valuesInline:
      secret:
        create: false
        name: linkding-secrets
      ingressRoute:
        host: bookmarks.hefler.dev
