apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: linkding
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: linkding
      app.kubernetes.io/instance: linkding
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 9090
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: databases
          podSelector:
            matchLabels:
              app.kubernetes.io/name: postgres
              app.kubernetes.io/instance: postgres
      ports:
        - protocol: TCP
          port: 5432
    # Allow outbound HTTPS for external links and integrations.
    - ports:
        - protocol: TCP
          port: 443
