apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: databases

secretGenerator:
  - name: postgres-secrets
    envs:
      - .env

configMapGenerator:
  - name: postgres-scripts
    files:
      - scripts/01-init-script.sh

resources:
  - statefulset.yaml
  - service.yaml
  - networkpolicy.yaml
