apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus # Ensure dashboards refer to this
    access: proxy
    url: http://prometheus.monitoring.svc.cluster.local:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      allowAsRecordingRulesTarget: true
      prometheusType: Prometheus
      prometheusVersion: 3.9.1
      cacheLevel: "High"
      disableRecordingRules: false
      timeInterval: 15s # Prometheus scrape interval
      incrementalQueryOverlapWindow: 10m
